keycodes = {
            "Strg": 17,                                 # Shloud be 17
            "Umschalt": 16,
            "Alt": 18,                                  # Shloud be 18
            "Backspace": 8,
            "Esc": 27,
            "Leertaste": 32,
            "BildAuf": 33,
            "BildAb": 34,
            "Ende": 35,
            "Pos1": 36,
            "PfeilLinks": 37,
            "PfeilOben": 38,
            "PfeilRechts": 39,
            "PfeilUnten": 40,
            "Enter": 13,
            "0": 48,
            "1": 49,
            "2": 50,
            "3": 51,
            "4": 52,
            "5": 53,
            "6": 54,
            "7": 55,
            "8": 56,
            "9": 57,
            "D": 68,
            "G": 71,
            "K": 75,
            "M": 77,
            "Q": 81,
            "Multiplizieren": 106,
            "Addieren": 107,
            "Subtrahieren": 109,
            "Dezimal": 110,
            "Dividieren": 111,
            "F11": 122,
            "TAB": 9,               # Nach TAB alle folgenden Tasten sind für erweiteret Funktionen. 
            ",": 188,
            ".": 190,
            "/": 191,
            "B": 66,
            "R": 82,
            "A": 65,
            "S": 83,
            "X": 88,
            "I": 73,
            "L": 76,
            "Y": 89,
            "T": 84,
            "W": 87,
            "N": 78,
            "P": 80,
            "Einfg": 45,
            "Entf": 46
        }